version: "3.8"
services:
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      target: app
      args:
        PHP_VERSION: "8.0"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      COMPOSER_ENTRYPOINT_SCRIPT: setup
      XDEBUG_CONFIG: "${XDEBUG_CONFIG:-client_host=host.docker.internal}"
      XDEBUG_MODE: "${XDEBUG_MODE:-develop,debug,coverage,trace}"
